---
# This handler for base rol, will configure epel repository.

- name: Disable Selinux
  selinux: state=disabled

- name: Update Server
  yum: name=* state=latest

- name: Copy epel repo file
  template: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Restart server before yum Update
  command: shutdown -r now "Ansible - Yum Update"
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server.
  local_action:
      module: wait_for
        host=192.168.122.10
        port=22
        delay=1
        timeout=300
