---
# Tasks to install icinga2 and icinga2web

- name: Install MySQL/MariaDB Server
  yum: name={{ item }} state=installed
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python

- name: Creating Mysql/MariaDB configuration file based in template
  template: src=my.cnf dest=/etc/my.cnf
  notify: 
   - restart mariadb

- name: Creating MySQL/MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Create MySQL/MariaDB pid file
  file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0775

- name: Starting MySQL/MariaDB service
  service: name=mariadb state=started enabled=yes

- name: Change root password
  mysql_user: login_user=root login_password='' name=root password={{ mysql_root_password }} priv=*.*:ALL,GRANT host={{ item }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  notify:
    - restart mariadb

- name: Creating Icinga Database
  mysql_db: name={{ dbname }} state=present

- name: Creating IcingaWeb Database
  mysql_db: name={{ webdbname }} state=present

- name: Creating Icinga DB user
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv={{ dbname }}.*:ALL host='localhost' state=present

- name: Creating IcingaWeb DB user
  mysql_user: name={{ webdbuser }} password={{ webdbpassword }} priv={{ webdbname }}.*:ALL host='localhost' state=present

- name: Install Icinga2
  yum: name={{ item }} state=installed
  with_items:
    - icinga2
    - icingaweb2
    - icingacli
    - icinga2-ido-mysql
    - httpd
    - nagios-plugins-all
    - php-ldap

- name: start and enable icinga2
  service: name=icinga2 state=started enabled=yes
  
- name: start and enable httpd
  service: name=httpd state=started enabled=yes

- name: Setting up firewall rules for http
  firewalld: service=http permanent=true state=enabled 

- name: Setting up firewall rules for https
  firewalld: service=https permanent=true state=enabled

- name: Loading Icinga2 MySQL Schema
  mysql_db: state=import name=icinga2 target=/usr/share/icinga2-ido-mysql/schema/mysql.sql

- name: Copy icinga2-ido-mysql configuration from template.
  template: src=ido-mysql.conf dest=/etc/icinga2/features-available/ido-mysql.conf backup=yes owner=icinga group=icinga mode=0640

- name: Setting up date.timezone in php.ini
  lineinfile: dest=/etc/php.ini regexp=';date.timezone' insertbefore=";date.timezone" line="date.timezone = \"America/Lima\""

- name: Enabling icinga2-ido-mysql
  command: "icinga2 feature enable ido-mysql"
  notify: 
   - restart icinga2

- name: Restart HTTPD to enable datetime and php-ldap module
  service: name=httpd state=restarted

- name: Finishing Icinga2 and Icinga2Web Installation
  debug: msg="Now execute the following command to generate a setup token 'icincagli setup token create' and go to http://server_ip/icingaweb2/setup to finish icinga2 configuration"
