---
# This handler for docker rol, will install docker
- name: Install docker
  yum: name={{ item }} state=latest
  with_items:
    - docker
    - docker-registry
    - python-docker-py

- name: Install docker-registry
  yum: name=docker-registry state=latest

- name: start and enable docker
  service: name=docker state=started enabled=yes

- name: Creating containers repository
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - "/containers/apache2"
    - "/containers/mysql"

- name: Copy files to Apache2 container
  copy: src={{ item }} dest="/containers/apache2/{{ item }}"
  with_items:
    - "Dockerfile.apache2"
    - "run-httpd.sh"

- name: Rename Dockerfile.apache2 to Dockerfile
  command: mv /containers/apache2/Dockerfile.apache2 /containers/apache2/Dockerfile

- name: Build Apache2 Container
  docker_image: path="/containers/apache2" name="abendezub/apache2" state=build

- name: Copy files to MySQL container
  copy: src={{ item }} dest="/containers/mysql/{{ item }}"
  with_items:
    - "Dockerfile.mysql"

- name: Rename Dockerfile.mysql to Dockerfile
  command: mv /containers/mysql/Dockerfile.mysql /containers/mysql/Dockerfile

- name: Build MySQL/MariaDB container
  docker_image: path="/containers/mysql" name="abendezub/mysql" state=build

- name: Start Apache2 Container and mapped to port TCP/80 in host
  docker_image: path="/containers/mysql" name="abendezub/apache2" state=present
