---
# This handler for Wildfly rol. Will install JDK and Wildfly Application server, additional it will configure the app server.

- name: Install Java 1.7 and some dependencies
  yum: name={{ item }} state=present
  with_items:
    - unzip
    - java-1.8.0-openjdk

- name: Download and Extract Wildfly 10
  unarchive: src=http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.tar.gz dest=/opt copy=no

- name: Rename Wilfdly Folder
  command: chdir=/opt /bin/mv wildfly-10.0.0.Final wilfdly create=/opt/wildfly

- name: Add group wildfly
  group: name=wildfly

- name: Add user wildfly
  user: name=wildfly group=wildfly home=/opt/wildly

- name: Change ownership for wildly folder to recenctly created user.
  file: path=/opt/wildfly owner=wildfly group=wildfly state=directory recurse=yes

- name: Configuring Daemon options
  file:
